
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symDatos {
  /* terminals */
  public static final int rclaves = 10;
  public static final int coma = 5;
  public static final int numerico = 9;
  public static final int llavecerrada = 7;
  public static final int cadena = 8;
  public static final int corchetecerrado = 4;
  public static final int EOF = 0;
  public static final int llaveabierta = 6;
  public static final int corcheteabierto = 3;
  public static final int error = 1;
  public static final int rregistros = 11;
  public static final int igual = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igual",
  "corcheteabierto",
  "corchetecerrado",
  "coma",
  "llaveabierta",
  "llavecerrada",
  "cadena",
  "numerico",
  "rclaves",
  "rregistros"
  };
}

