
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symReportes {
  /* terminals */
  public static final int rpromedio = 18;
  public static final int parentesiscerrado = 5;
  public static final int cadena = 25;
  public static final int rimprimir = 22;
  public static final int mayoroigual = 9;
  public static final int rcontarsi = 19;
  public static final int diferentede = 12;
  public static final int parentesisabierto = 4;
  public static final int robtenersi = 20;
  public static final int coma = 6;
  public static final int dobleigual = 11;
  public static final int rcadena = 14;
  public static final int rnumerico = 13;
  public static final int rsumar = 16;
  public static final int menoroigual = 10;
  public static final int numerico = 24;
  public static final int menor = 8;
  public static final int igual = 2;
  public static final int EOF = 0;
  public static final int id = 26;
  public static final int rarchivo = 15;
  public static final int rgraficar = 23;
  public static final int error = 1;
  public static final int rleerarchivo = 21;
  public static final int rcontar = 17;
  public static final int puntoycoma = 3;
  public static final int mayor = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igual",
  "puntoycoma",
  "parentesisabierto",
  "parentesiscerrado",
  "coma",
  "mayor",
  "menor",
  "mayoroigual",
  "menoroigual",
  "dobleigual",
  "diferentede",
  "rnumerico",
  "rcadena",
  "rarchivo",
  "rsumar",
  "rcontar",
  "rpromedio",
  "rcontarsi",
  "robtenersi",
  "rleerarchivo",
  "rimprimir",
  "rgraficar",
  "numerico",
  "cadena",
  "id"
  };
}

