/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author aybso
 */
public class Main_Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Main_Interfaz
     */
    
    public static String path_file;
    public static LinkedList<Object> lista_instrucciones;
    public static LinkedList<Errores> lista_errores = new LinkedList();
    
    
    public Main_Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenuItem();
        opcionGuardarComo = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        opcionReportes = new javax.swing.JMenu();
        opcionCompilar = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OLC1 Practica 1");

        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane3.setViewportView(consola);

        editor.setColumns(20);
        editor.setRows(5);
        jScrollPane1.setViewportView(editor);

        jMenu2.setText("Archivo");

        opcionAbrir.setText("Abrir");
        opcionAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAbrirActionPerformed(evt);
            }
        });
        jMenu2.add(opcionAbrir);

        opcionGuardarComo.setText("Guardar");
        jMenu2.add(opcionGuardarComo);

        jMenuItem4.setText("Guardar Como");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        opcionReportes.setText("Reportes");
        jMenuBar1.add(opcionReportes);

        opcionCompilar.setText("Compilar");
        opcionCompilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionCompilarMouseClicked(evt);
            }
        });
        jMenuBar1.add(opcionCompilar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAbrirActionPerformed

        try {

            JFileChooser archivo = new JFileChooser();
            archivo.showOpenDialog(this);
            File file = archivo.getSelectedFile();
            path_file = file.getPath();


            if (file != null) {
                FileReader open = new FileReader(file);
                BufferedReader read = new BufferedReader(open);
                String txt = "", aux = "";
                    
                while((txt=read.readLine()) != null){
                    aux += txt + "\n";
                }
                
                read.close();
                editor.removeAll();
                editor.append(aux);
            }

            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main_Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No se encontro el archivo");
        } catch (IOException ex) {
            Logger.getLogger(Main_Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No se encontro el archivo");
        }


    }//GEN-LAST:event_opcionAbrirActionPerformed

    private void opcionCompilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionCompilarMouseClicked
        try {
            Analizador analizar = new Analizador(path_file);
            lista_instrucciones = analizar.getLista();
            
            
            consola.setText("");
            consola.append("Hay " + lista_instrucciones.size() + " instrucciones\n");
            for(Object o: lista_instrucciones){
                consola.append(o.getClass() + "\n");
            }
            
          
            /* FUNCION LEER ARCHIVO QUE DEVUELVE UNA MATRIZ CON LA INFORMACIÓN
            * LeerArchivo d = new LeerArchivo("C:/Users/aybso/Downloads/Ejemplo_Entrada_Práctica1/articulos.dat");
            */
            
            
            
            consola.append("-------------ERRORES ------------------\n");
            for(Errores error: lista_errores){
                consola.append(error.getDescripcion() + " - Linea " + error.getValor() + "\n");
            }
            
        } catch (Exception ex) {
            consola.setText("");
            consola.setText("Error en la compilación\n");
            for(Errores error: lista_errores){
                consola.append(error.getDescripcion() + "\n");
            }
            Logger.getLogger(Main_Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opcionCompilarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consola;
    private javax.swing.JTextArea editor;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenu opcionCompilar;
    private javax.swing.JMenuItem opcionGuardarComo;
    private javax.swing.JMenu opcionReportes;
    // End of variables declaration//GEN-END:variables
}
